
import Link from 'next/link';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className=" w-full bg-teal-600 text-[40px] flex justify-center items-center gap-2.5">
          <Link href='/'>Home</Link>
          <Link href='/posts'>Posts</Link>
          <Link href='/articles'>Articles</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
